---
title: "data visualization"
format: html
---

## Load packages

```{r}
library(readr)
library(here)
library(dplyr)
library(tidyr)
library(forcats)
library(janitor)
library(ggplot2)
library(plotly)
library(DT)
library(leaflet)
```

## Load data

```{r}
# read in data from tinyurl link
delta_visits_raw <- read_csv(here("data/Socioecological_monitoring_data.csv"))
```

## Explore the data 

```{r}
colnames(delta_visits_raw)
glimpse(delta_visits_raw)
```

## Clean up data

```{r}
delta_visits <- delta_visits_raw %>% 
    clean_names()
delta_visits
```

```{r}
visits_long <- delta_visits %>% 
    pivot_longer(
        col = c(sm_boat,med_boat, lrg_boat, bank_angler, scientist, cars),
        names_to = "visitor_type", 
        values_to = "quantity"
    ) %>% 
    rename(restore_loc = eco_restore_approximate_location) %>% 
    select(-notes)
glimpse(visits_long)
```

```{r}
daily_visits_loc <- visits_long %>% 
    group_by(restore_loc, date, visitor_type) %>% 
    summarize(daily_visits = sum(quantity),.groups = "drop")
glimpse(daily_visits_loc)
```

## Make some plots

```{r}
daily_visits_loc %>% 
    filter(daily_visits < 30,
            visitor_type %in% c("sm_boat", "med_boat", "lrg_boat")) %>% 
    ggplot(aes(x = restore_loc, y = daily_visits))+
     geom_col(color='red', 
            fill='steelblue') 
```

```{r}
daily_visits_loc %>% 
    filter(daily_visits < 30,
            visitor_type %in% c("sm_boat", "med_boat", "lrg_boat")) %>% 
    ggplot(aes(x = restore_loc, y = daily_visits))+
     geom_col(aes(fill = visitor_type),
     color='red') 
```

```{r}
daily_visits_loc %>% 
    ggplot(aes(y = restore_loc, x = daily_visits, fill = visitor_type))+
    geom_col()+
    labs(
        x = "Number of Visits",
        y = "Restoration Location",
        fill = "Visitor type",
        title = "Total Visits to the restoration areas...",
        subtitle = " Sum of all visits between July and March 2018"
    ) +
    scale_x_continuous(breaks = seq(0,120,20), expand = c(0,0)) + 
    theme_minimal()+
    theme(
    legend.position = "right",
    axis.ticks.y = element_blank()
    )
```

```{r}
daily_visits_totals <- daily_visits_loc %>%
  group_by(restore_loc) %>%
  mutate(total = sum(daily_visits)) %>%
  ungroup() %>%
  mutate(restore_loc = fct_reorder(restore_loc, desc(total)))

unique(daily_visits_totals$restore_loc)
```

```{r}
my_theme <- function(base_size = 14) {
    theme_minimal(base_size = base_size) +
    theme(legend.position = "bottom", 
          panel.grid.major = element_line(color = 'slateblue1'))
}

ggplot(data = daily_visits_totals,
       aes(y = restore_loc, x = daily_visits, fill = visitor_type)) +
  geom_col() +
  scale_fill_viridis_d() +
  scale_x_continuous(breaks = seq(0, 120, 20), expand = c(0, 0)) +
  labs(
    x = "Number of Visits",
    y = "Restoration Location",
    fill = "Visitor Type",
    title = "Total Visits to Delta Restoration Areas by Visitor Type",
    subtitle = "Sum of all visits during the study period"
  ) +
  my_theme()
```

```{r}
##ggsave("figures/visit_restore_site_delta.jpg", width = 12, height = 6, units = "in")
```

```{r}
facet_plot <- ggplot(data = daily_visits_totals,
       aes(x = visitor_type, y = daily_visits,
           fill = visitor_type)) +
    geom_col() +
    facet_wrap(~restore_loc,
               scales = "free_y",
               ncol   = 5,
               nrow   = 2) +
    scale_fill_viridis_d() +
    labs(x        = "Type of visitor",
         y        = "Number of Visits",
         title    = "Total Number of Visits to Delta Restoration Areas",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.x    = element_blank(),
          axis.text.x     = element_blank())

facet_plot
```


```{r}
facet_plot <- ggplot(data = daily_visits_loc,
       aes(x = visitor_type, y = daily_visits,
           fill = visitor_type)) +
    geom_col() +
    facet_wrap(~restore_loc,
               scales = "free_y",
               ncol   = 5,
               nrow   = 2) +
    scale_fill_viridis_d() +
    labs(x        = "Type of visitor",
         y        = "Number of Visits",
         title    = "Total Number of Visits to Delta Restoration Areas",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.x    = element_blank(),
          axis.text.x     = element_blank())
facet_plot
```

## show an interactive 

```{r}

delta_visits_raw <- read_csv(here("data/Socioecological_monitoring_data.csv"),
                             show_col_types = FALSE)

daily_visits_loc <- delta_visits_raw %>%
  janitor::clean_names() %>%
  tidyr::pivot_longer(
    cols      = c(sm_boat, med_boat, lrg_boat, bank_angler, scientist, cars),
    names_to  = "visitor_type",
    values_to = "quantity"
  ) %>%
  dplyr::rename(restore_loc = eco_restore_approximate_location) %>%
  dplyr::select(-notes) %>%
  dplyr::group_by(restore_loc, date, visitor_type) %>%
  dplyr::summarize(daily_visits = sum(quantity), .groups = "drop")

```

## Interactive Table

```{r}
DT::datatable(
  daily_visits_loc,
  caption  = "Daily visitor counts at Delta restoration sites",
  colnames = c("Location", "Date", "Visitor type", "Daily visits"),
  options  = list(pageLength = 10)
)
```

## show an interactive map

## Interactive Map

```{r}
restoration_sites <- delta_visits_raw %>%
  janitor::clean_names() %>%
  distinct(restore_loc = eco_restore_approximate_location,
           latitude, longitude) %>%
  drop_na(latitude, longitude)

leaflet(restoration_sites) %>%
  addTiles() %>%
  addMarkers(
    lng   = ~longitude,
    lat   = ~latitude,
    popup = ~restore_loc
  )
```



```{r}
leaflet(restoration_sites) %>%
  addTiles() %>%
  addCircleMarkers(
    lng         = ~longitude,
    lat         = ~latitude,
    popup       = ~restore_loc,
    radius      = 8,
    fillColor   = "steelblue",
    fillOpacity = 0.8,
    stroke      = FALSE
  )
```

